/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User.Frontend;

import User.Backend.DatabaseHelper;
import User.Backend.QueueHandler;
import User.Backend.ServerConnector;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import java.awt.Image;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author Rping
 */
public class UserWelcome extends javax.swing.JFrame implements WindowListener {
    private static ServerConnector server;

    /**
     * Creates new form Welcome
     */
    public static void startSocket(){
        server = new ServerConnector();
        server.start();
    }

    public static void stopSocket() {
        server.interrupt();
    }

    public static void notifySocket() {
        synchronized (server) {
            server.notify();
        }
    }

    public UserWelcome() {
        try(FileReader fr = new FileReader("roomid.conf");
            BufferedReader br = new BufferedReader(fr)) {
            System.out.println("Configuration found, loading...");
            String roomId = Integer.toString(Integer.parseInt(br.readLine()));
            UserSite.setRoomId(roomId);

        } catch (IOException | NumberFormatException ignored) {
            try(FileWriter fw = new FileWriter("roomid.conf");
                BufferedWriter bw = new BufferedWriter(fw)) {
                bw.write("-\n# Replace - with this room's id");
            } catch (IOException exception) {
                exception.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Please set room id in roomid.conf", "Room ID isn't configured!", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }

        startSocket();
        initComponents();
        setClientName("Connecting...");
        this.addWindowListener(this);
        String customerName = DatabaseHelper.getRoomData(UserSite.getRoomId());
        setClientName(customerName);
        UserSite.setCustomerName(customerName);
        ImageIcon setWallIcon = new ImageIcon(new ImageIcon(getClass().getResource("/Assets/wallpaper3.jpg")).getImage().getScaledInstance(150, 415, Image.SCALE_SMOOTH));
        this.jLabel1.setText("");
        this.jLabel1.setIcon(setWallIcon);
        this.jLabel2.setText("");
        this.jLabel2.setIcon(setWallIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        continueButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        ClientNameLabel = new javax.swing.JLabel();
        instuctionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(56, 86, 116));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(left, java.awt.BorderLayout.LINE_START);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
        right.setLayout(rightLayout);
        rightLayout.setHorizontalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        rightLayout.setVerticalGroup(
            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(right, java.awt.BorderLayout.LINE_END);

        body.setBackground(new java.awt.Color(56, 86, 116));

        continueButton.setBackground(new java.awt.Color(153, 219, 255));
        continueButton.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        continueButton.setText("Continue");
        continueButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Angsana New", 1, 56)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome!");

        ClientNameLabel.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        ClientNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ClientNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClientNameLabel.setText("Mr. Asama Courage to sell");

        instuctionLabel.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        instuctionLabel.setForeground(new java.awt.Color(255, 255, 255));
        instuctionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instuctionLabel.setText("\"Hotel Food Delivery Program\"");

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bodyLayout.createSequentialGroup()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(instuctionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(ClientNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClientNameLabel)
                .addGap(60, 60, 60)
                .addComponent(instuctionLabel)
                .addGap(35, 35, 35)
                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jPanel2.add(body, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        if(evt.getSource().equals(continueButton)){
            UserSite si = new UserSite();
            si.pack();
            si.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ignored) { }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserWelcome().setVisible(true);
            }
        });
    }

    public static void setClientName(String name) {
        ClientNameLabel.setText(name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel ClientNameLabel;
    private javax.swing.JPanel body;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel instuctionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel left;
    private javax.swing.JPanel right;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {

    }

    @Override
    public void windowClosing(WindowEvent e) {
        stopSocket();
    }

    @Override
    public void windowClosed(WindowEvent e) {

    }

    @Override
    public void windowIconified(WindowEvent e) {

    }

    @Override
    public void windowDeiconified(WindowEvent e) {

    }

    @Override
    public void windowActivated(WindowEvent e) {

    }

    @Override
    public void windowDeactivated(WindowEvent e) {

    }
}
