/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User.Frontend;

import User.Backend.QueueHandler;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

import java.awt.*;
import java.awt.event.MouseEvent;
import java.text.MessageFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rping
 */
public class UserSite extends javax.swing.JFrame {
    private static String roomId;

    private static String customerName;

    /**
     * Creates new form UserSite
     */
    public UserSite() {
        initComponents();
        orderList = new JSONArray();
        jTable1.setModel(new DefaultTableModel(new Vector<Vector<String>>(), getColumnNames()));

        int floor;
        try {
            floor = Integer.parseInt(roomId.substring(0, 1));
        } catch (IndexOutOfBoundsException ignored) {
            floor = 0;
        };
        RoomLabel.setText(MessageFormat.format("ห้อง {0}  ชั้น {1}", roomId, floor));
        ClientNameLabel.setText("Hello, " + customerName);

        ImageIcon menu1 = new ImageIcon(new ImageIcon(getClass().getResource("/Assets/food1.jpg")).getImage().getScaledInstance((int)(this.foodPic1.getWidth()*0.9), (int)(this.foodPic1.getHeight()*0.7), Image.SCALE_SMOOTH));
        ImageIcon menu2 = new ImageIcon(new ImageIcon(getClass().getResource("/Assets/food2.jpg")).getImage().getScaledInstance((int)(this.foodPic1.getWidth()*0.9), (int)(this.foodPic1.getHeight()*0.7), Image.SCALE_SMOOTH));
        ImageIcon menu3 = new ImageIcon(new ImageIcon(getClass().getResource("/Assets/food3.jpg")).getImage().getScaledInstance((int)(this.foodPic1.getWidth()*0.9), (int)(this.foodPic1.getHeight()*0.7), Image.SCALE_SMOOTH));
        ImageIcon menu4 = new ImageIcon(new ImageIcon(getClass().getResource("/Assets/food4.jpg")).getImage().getScaledInstance((int)(this.foodPic1.getWidth()*0.9), (int)(this.foodPic1.getHeight()*0.7), Image.SCALE_SMOOTH));
        ImageIcon menu5 = new ImageIcon(new ImageIcon(getClass().getResource("/Assets/food5.jpg")).getImage().getScaledInstance((int)(this.foodPic1.getWidth()*0.9), (int)(this.foodPic1.getHeight()*0.7), Image.SCALE_SMOOTH));
        ImageIcon menu6 = new ImageIcon(new ImageIcon(getClass().getResource("/Assets/food6.jpg")).getImage().getScaledInstance((int)(this.foodPic1.getWidth()*0.9), (int)(this.foodPic1.getHeight()*0.7), Image.SCALE_SMOOTH));
        this.foodPic1.setText("");
        this.foodPic1.setIcon(menu1);

        this.foodPic2.setText("");
        this.foodPic2.setIcon(menu2);

        this.foodPic3.setText("");
        this.foodPic3.setIcon(menu3);

        this.foodPic4.setText("");
        this.foodPic4.setIcon(menu4);

        this.foodPic5.setText("");
        this.foodPic5.setIcon(menu5);

        this.foodPic6.setText("");
        this.foodPic6.setIcon(menu6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top = new javax.swing.JPanel();
        ClientNameLabel = new javax.swing.JLabel();
        RoomLabel = new javax.swing.JLabel();
        left = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        clearButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        grid1 = new javax.swing.JPanel();
        foodPic1 = new javax.swing.JLabel();
        gr1bot = new javax.swing.JPanel();
        food1 = new javax.swing.JButton();
        grid2 = new javax.swing.JPanel();
        foodPic2 = new javax.swing.JLabel();
        gr2bot = new javax.swing.JPanel();
        food2 = new javax.swing.JButton();
        grid3 = new javax.swing.JPanel();
        foodPic3 = new javax.swing.JLabel();
        gr3bot = new javax.swing.JPanel();
        food3 = new javax.swing.JButton();
        grid4 = new javax.swing.JPanel();
        foodPic4 = new javax.swing.JLabel();
        gr4bot = new javax.swing.JPanel();
        food4 = new javax.swing.JButton();
        grid5 = new javax.swing.JPanel();
        foodPic5 = new javax.swing.JLabel();
        gr5bot = new javax.swing.JPanel();
        food5 = new javax.swing.JButton();
        grid6 = new javax.swing.JPanel();
        foodPic6 = new javax.swing.JLabel();
        gr6bot = new javax.swing.JPanel();
        food6 = new javax.swing.JButton();
        bot = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        top.setBackground(new java.awt.Color(56, 86, 116));

        ClientNameLabel.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        ClientNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ClientNameLabel.setText("Mr. Asama Courage to sell");

        RoomLabel.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        RoomLabel.setForeground(new java.awt.Color(255, 255, 255));
        RoomLabel.setText("ห้อง 101  ชั้น 1");

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(RoomLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 482, Short.MAX_VALUE)
                .addComponent(ClientNameLabel)
                .addGap(46, 46, 46))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClientNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        getContentPane().add(top, java.awt.BorderLayout.NORTH);

        left.setBackground(new java.awt.Color(227, 234, 240));

        jTable1.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        clearButton.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        clearButton.setText("Clear");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        submitButton.setText("Submit");
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(15, 15, 15)
                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(submitButton))
                .addGap(15, 15, 15))
        );

        getContentPane().add(left, java.awt.BorderLayout.WEST);

        body.setBackground(new java.awt.Color(227, 234, 240));
        body.setLayout(new java.awt.GridLayout(2, 3));

        grid1.setLayout(new java.awt.BorderLayout());

        foodPic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodPic1.setText("img");
        grid1.add(foodPic1, java.awt.BorderLayout.CENTER);

        food1.setFont(new java.awt.Font("Angsana New", 0, 22)); // NOI18N
        food1.setText("ข้าวกระเพราไก่");
        food1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        food1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gr1botLayout = new javax.swing.GroupLayout(gr1bot);
        gr1bot.setLayout(gr1botLayout);
        gr1botLayout.setHorizontalGroup(
            gr1botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(gr1botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr1botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        gr1botLayout.setVerticalGroup(
            gr1botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(gr1botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr1botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        grid1.add(gr1bot, java.awt.BorderLayout.SOUTH);

        body.add(grid1);

        grid2.setLayout(new java.awt.BorderLayout());

        foodPic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodPic2.setText("img");
        grid2.add(foodPic2, java.awt.BorderLayout.CENTER);

        food2.setFont(new java.awt.Font("Angsana New", 0, 22)); // NOI18N
        food2.setText("ข้าวไก่กระเทียม");
        food2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        food2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gr2botLayout = new javax.swing.GroupLayout(gr2bot);
        gr2bot.setLayout(gr2botLayout);
        gr2botLayout.setHorizontalGroup(
            gr2botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(gr2botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr2botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        gr2botLayout.setVerticalGroup(
            gr2botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(gr2botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr2botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        grid2.add(gr2bot, java.awt.BorderLayout.SOUTH);

        body.add(grid2);

        grid3.setLayout(new java.awt.BorderLayout());

        foodPic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodPic3.setText("img");
        grid3.add(foodPic3, java.awt.BorderLayout.CENTER);

        food3.setFont(new java.awt.Font("Angsana New", 0, 22)); // NOI18N
        food3.setText("ข้าวผัดหมู");
        food3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        food3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gr3botLayout = new javax.swing.GroupLayout(gr3bot);
        gr3bot.setLayout(gr3botLayout);
        gr3botLayout.setHorizontalGroup(
            gr3botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(gr3botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr3botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        gr3botLayout.setVerticalGroup(
            gr3botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(gr3botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr3botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        grid3.add(gr3bot, java.awt.BorderLayout.SOUTH);

        body.add(grid3);

        grid4.setLayout(new java.awt.BorderLayout());

        foodPic4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodPic4.setText("img");
        grid4.add(foodPic4, java.awt.BorderLayout.CENTER);

        food4.setFont(new java.awt.Font("Angsana New", 0, 22)); // NOI18N
        food4.setText("ข้าวแกงกะหรี่หมูทอด");
        food4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        food4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gr4botLayout = new javax.swing.GroupLayout(gr4bot);
        gr4bot.setLayout(gr4botLayout);
        gr4botLayout.setHorizontalGroup(
            gr4botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(gr4botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr4botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        gr4botLayout.setVerticalGroup(
            gr4botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(gr4botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr4botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        grid4.add(gr4bot, java.awt.BorderLayout.SOUTH);

        body.add(grid4);

        grid5.setLayout(new java.awt.BorderLayout());

        foodPic5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodPic5.setText("img");
        grid5.add(foodPic5, java.awt.BorderLayout.CENTER);

        food5.setFont(new java.awt.Font("Angsana New", 0, 22)); // NOI18N
        food5.setText("โจ้กหมู");
        food5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        food5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gr5botLayout = new javax.swing.GroupLayout(gr5bot);
        gr5bot.setLayout(gr5botLayout);
        gr5botLayout.setHorizontalGroup(
            gr5botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(gr5botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr5botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        gr5botLayout.setVerticalGroup(
            gr5botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(gr5botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr5botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        grid5.add(gr5bot, java.awt.BorderLayout.SOUTH);

        body.add(grid5);

        grid6.setLayout(new java.awt.BorderLayout());

        foodPic6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodPic6.setText("img");
        grid6.add(foodPic6, java.awt.BorderLayout.CENTER);

        food6.setFont(new java.awt.Font("Angsana New", 0, 22)); // NOI18N
        food6.setText("ข้าวต้มกุ้ง");
        food6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        food6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gr6botLayout = new javax.swing.GroupLayout(gr6bot);
        gr6bot.setLayout(gr6botLayout);
        gr6botLayout.setHorizontalGroup(
            gr6botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(gr6botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr6botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        gr6botLayout.setVerticalGroup(
            gr6botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(gr6botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gr6botLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(food6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        grid6.add(gr6bot, java.awt.BorderLayout.SOUTH);

        body.add(grid6);

        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        bot.setBackground(new java.awt.Color(67, 106, 141));
        bot.setPreferredSize(new java.awt.Dimension(1047, 30));

        javax.swing.GroupLayout botLayout = new javax.swing.GroupLayout(bot);
        bot.setLayout(botLayout);
        botLayout.setHorizontalGroup(
            botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1047, Short.MAX_VALUE)
        );
        botLayout.setVerticalGroup(
            botLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(bot, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void food1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food1ActionPerformed
        if(evt.getSource().equals(food1)){
            genOrder("ข้าวกระเพราไก่");
        }
    }//GEN-LAST:event_food1ActionPerformed

    private void food2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food2ActionPerformed
        if(evt.getSource().equals(food2)){
            genOrder("ข้าวไก่กระเทียม");
        }
    }//GEN-LAST:event_food2ActionPerformed

    private void food3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food3ActionPerformed
        if(evt.getSource().equals(food3)){
            genOrder("ข้าวผัดหมู");
        }
    }//GEN-LAST:event_food3ActionPerformed

    private void food4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food4ActionPerformed
        if(evt.getSource().equals(food4)){
            genOrder("ข้าวแกงกระหรี่หมูทอด");
        }
    }//GEN-LAST:event_food4ActionPerformed

    private void food5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food5ActionPerformed
        if(evt.getSource().equals(food5)){
            genOrder("โจ้กหมู");
        }
    }//GEN-LAST:event_food5ActionPerformed

    private void food6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food6ActionPerformed
        if(evt.getSource().equals(food6)){
            genOrder("ข้าวต้มกุ้ง");
        }
    }//GEN-LAST:event_food6ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        if(evt.getSource().equals(clearButton)){
            orderList.clear();
            jTable1.setModel(new DefaultTableModel(new Vector<Vector<String>>(), getColumnNames()));
        }
    }//GEN-LAST:event_clearButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if(orderList.size() == 0) return;
        JSONObject order = new JSONObject();
        order.put("type", "food_order");
        order.put("order", orderList);
        QueueHandler.pushQueues(order);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void genOrder(String food) {
        boolean found = false;
        for (int i = 0; i < orderList.size(); i++) {
            JSONObject item = (JSONObject) orderList.get(i);
            if(food.equals(item.get("name"))) {
                item.put("count", (int) item.get("count")+1);
                orderList.remove(i);
                orderList.add(i, item);

                found = true;
                break;
            }
        }
        if(!found) {
            JSONObject order = new JSONObject();
            order.put("name", food);
            order.put("count", 1);
            orderList.add(order);
        }

        Vector<Vector<String>> data = new Vector<Vector<String>>();
        for (int row = 0; row < orderList.size(); row++) {
            Vector<String> vector = new Vector<String>();
            JSONObject order = ((JSONObject)orderList.get(row));
            vector.add(Integer.toString(row+1));
            vector.add(order.get("name").toString());
            vector.add(order.get("count").toString());
            data.add(vector);
        }

        jTable1.setModel(new DefaultTableModel(data, getColumnNames()));
    }

    private Vector<String> getColumnNames() {
        Vector<String> columnNames = new Vector<String>();
        columnNames.add("No.");
        columnNames.add("Food");
        columnNames.add("Count");
        return columnNames;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSite().setVisible(true);
            }
        });
    }

    public static String getRoomId() {
        return roomId;
    }

    public static void setRoomId(String roomId) {
        UserSite.roomId = roomId;
    }

    public static void setCustomerName(String customerName) {
        UserSite.customerName = customerName;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientNameLabel;
    private static javax.swing.JLabel RoomLabel;
    private javax.swing.JPanel body;
    private javax.swing.JPanel bot;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton food1;
    private javax.swing.JButton food2;
    private javax.swing.JButton food3;
    private javax.swing.JButton food4;
    private javax.swing.JButton food5;
    private javax.swing.JButton food6;
    private javax.swing.JLabel foodPic1;
    private javax.swing.JLabel foodPic2;
    private javax.swing.JLabel foodPic3;
    private javax.swing.JLabel foodPic4;
    private javax.swing.JLabel foodPic5;
    private javax.swing.JLabel foodPic6;
    private javax.swing.JPanel gr1bot;
    private javax.swing.JPanel gr2bot;
    private javax.swing.JPanel gr3bot;
    private javax.swing.JPanel gr4bot;
    private javax.swing.JPanel gr5bot;
    private javax.swing.JPanel gr6bot;
    private javax.swing.JPanel grid1;
    private javax.swing.JPanel grid2;
    private javax.swing.JPanel grid3;
    private javax.swing.JPanel grid4;
    private javax.swing.JPanel grid5;
    private javax.swing.JPanel grid6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel left;
    private javax.swing.JButton submitButton;
    private javax.swing.JPanel top;
    private JSONArray orderList;
    // End of variables declaration//GEN-END:variables
}
