/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.Frontend;

/**
 *
 * @author Asus
 */
import Admin.Backend.DatabaseHelper;
import org.json.simple.JSONObject;

import java.sql.*;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Calendar;

public class RegisterForm extends javax.swing.JFrame {
    private Connection con;

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.bdate.setMaxDate(Calendar.getInstance());
        this.bdate.setDateFormat(new SimpleDateFormat("dd/MM/yyyy"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Head = new javax.swing.JPanel();
        jpageLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        minButton = new javax.swing.JLabel();
        jPasswordLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jFnameLabel = new javax.swing.JLabel();
        jFnameTextField = new javax.swing.JTextField();
        jRetypeLabel = new javax.swing.JLabel();
        jRetypeTextField = new javax.swing.JTextField();
        birthDateLabel = new javax.swing.JLabel();
        bdate = new datechooser.beans.DateChooserCombo();
        jRetypeLabel2 = new javax.swing.JLabel();
        jAddressField = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jUsernameLabel = new javax.swing.JLabel();
        jUsernameTextField = new javax.swing.JTextField();
        jLnameLabel = new javax.swing.JLabel();
        jLnameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(52, 116, 156));

        Head.setBackground(new java.awt.Color(16, 76, 113));

        jpageLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jpageLabel.setForeground(new java.awt.Color(255, 255, 255));
        jpageLabel.setText("Register Form");

        closeButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("x");
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        minButton.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        minButton.setForeground(new java.awt.Color(255, 255, 255));
        minButton.setText("-");
        minButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jpageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minButton)
                .addGap(26, 26, 26)
                .addComponent(closeButton)
                .addGap(29, 29, 29))
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minButton)
                    .addComponent(jpageLabel)
                    .addComponent(closeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPasswordLabel.setFont(new java.awt.Font("Angsana New", 1, 30)); // NOI18N
        jPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPasswordLabel.setText("Password:");

        jPasswordField1.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        jPasswordField1.setPreferredSize(new java.awt.Dimension(5, 42));

        createButton.setBackground(new java.awt.Color(0, 204, 255));
        createButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 102, 102));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jFnameLabel.setFont(new java.awt.Font("Angsana New", 1, 30)); // NOI18N
        jFnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jFnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jFnameLabel.setText("First Name:");

        jFnameTextField.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        jFnameTextField.setPreferredSize(new java.awt.Dimension(5, 42));
        jFnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFnameTextFieldActionPerformed(evt);
            }
        });

        jRetypeLabel.setFont(new java.awt.Font("Angsana New", 1, 30)); // NOI18N
        jRetypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        jRetypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jRetypeLabel.setText("Retype Pass:");

        jRetypeTextField.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        jRetypeTextField.setPreferredSize(new java.awt.Dimension(5, 42));
        jRetypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetypeTextFieldActionPerformed(evt);
            }
        });

        birthDateLabel.setFont(new java.awt.Font("Angsana New", 1, 30)); // NOI18N
        birthDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        birthDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        birthDateLabel.setText("Birth Date:");

        bdate.setCalendarPreferredSize(new java.awt.Dimension(500, 300));
        bdate.setNothingAllowed(false);
        bdate.setFieldFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        bdate.setNavigateFont(new java.awt.Font("Angsana New", java.awt.Font.PLAIN, 24));
        bdate.setCurrentNavigateIndex(0);

        jRetypeLabel2.setFont(new java.awt.Font("Angsana New", 1, 30)); // NOI18N
        jRetypeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jRetypeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jRetypeLabel2.setText("Address:");

        jTextArea1.setColumns(10);
        jTextArea1.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setMaximumSize(new java.awt.Dimension(2, 2));
        jTextArea1.setMinimumSize(new java.awt.Dimension(2, 2));
        jAddressField.setViewportView(jTextArea1);

        jUsernameLabel.setFont(new java.awt.Font("Angsana New", 1, 30)); // NOI18N
        jUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jUsernameLabel.setText("Username:");

        jUsernameTextField.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        jUsernameTextField.setPreferredSize(new java.awt.Dimension(5, 42));
        jUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameTextFieldActionPerformed(evt);
            }
        });

        jLnameLabel.setFont(new java.awt.Font("Angsana New", 1, 30)); // NOI18N
        jLnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLnameLabel.setText("Last Name:");

        jLnameTextField.setFont(new java.awt.Font("Angsana New", 0, 30)); // NOI18N
        jLnameTextField.setPreferredSize(new java.awt.Dimension(5, 42));
        jLnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLnameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRetypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRetypeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jFnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jRetypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jUsernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jLnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jAddressField)
                    .addComponent(bdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createButton)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jFnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnameLabel)
                    .addComponent(jLnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameLabel)
                    .addComponent(jUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRetypeLabel)
                    .addComponent(jRetypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(birthDateLabel)
                    .addComponent(bdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRetypeLabel2)
                    .addComponent(jAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(cancelButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLnameTextFieldActionPerformed

    private void jUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameTextFieldActionPerformed

    private void jRetypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRetypeTextFieldActionPerformed

    private void jFnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFnameTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
//        if (jPasswordField1.getPassword().equals(jRetypeTextField.getText())) {}
        JSONObject data = new JSONObject();
        data.put("username", jUsernameLabel.getText());
        data.put("password", jPasswordField1.getPassword());
        data.put("full_name", jFnameTextField.getText() + " " + jLnameTextField.getText());
        if(DatabaseHelper.addNewAdmin(data)) this.dispose();
    }//GEN-LAST:event_createButtonActionPerformed

    private void minButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minButtonMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minButtonMouseClicked

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Head;
    private datechooser.beans.DateChooserCombo bdate;
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel closeButton;
    private javax.swing.JButton createButton;
    private javax.swing.JScrollPane jAddressField;
    private javax.swing.JLabel jFnameLabel;
    private javax.swing.JTextField jFnameTextField;
    private javax.swing.JLabel jLnameLabel;
    private javax.swing.JTextField jLnameTextField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JLabel jRetypeLabel;
    private javax.swing.JLabel jRetypeLabel2;
    private javax.swing.JTextField jRetypeTextField;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jUsernameLabel;
    private javax.swing.JTextField jUsernameTextField;
    private javax.swing.JLabel jpageLabel;
    private javax.swing.JLabel minButton;
    // End of variables declaration//GEN-END:variables
}
