/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Asus
 */
public class Head extends javax.swing.JPanel {

    /**
     * Creates new form Head
     */
    public Head() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeadPanel3 = new javax.swing.JPanel();
        jNameLabel3 = new javax.swing.JLabel();

        jHeadPanel3.setBackground(new java.awt.Color(67, 106, 141));
        jHeadPanel3.setForeground(new java.awt.Color(85, 122, 149));
        jHeadPanel3.setFont(new java.awt.Font("Angsana New", 0, 36)); // NOI18N

        jNameLabel3.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jNameLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jNameLabel3.setText("นายปิง กล้าค้าขาย");

        javax.swing.GroupLayout jHeadPanel3Layout = new javax.swing.GroupLayout(jHeadPanel3);
        jHeadPanel3.setLayout(jHeadPanel3Layout);
        jHeadPanel3Layout.setHorizontalGroup(
            jHeadPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHeadPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jNameLabel3)
                .addContainerGap(548, Short.MAX_VALUE))
        );
        jHeadPanel3Layout.setVerticalGroup(
            jHeadPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jNameLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHeadPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHeadPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jHeadPanel;
    private javax.swing.JPanel jHeadPanel1;
    private javax.swing.JPanel jHeadPanel2;
    private javax.swing.JPanel jHeadPanel3;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JLabel jNameLabel1;
    private javax.swing.JLabel jNameLabel2;
    private javax.swing.JLabel jNameLabel3;
    // End of variables declaration//GEN-END:variables
}
