package GUI;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

public class Room extends javax.swing.JPanel {

    public Room() {
        initComponents();
        jDateLabel.setText(this.getDate());
    }
    
    public String getDate(){
        Date date = Calendar.getInstance().getTime();
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        return formatter.format(date);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPageHeadPanel = new javax.swing.JPanel();
        jPageLabel = new javax.swing.JLabel();
        jBodyPanel = new javax.swing.JPanel();
        jDateLabel = new javax.swing.JLabel();
        floor3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        R301 = new javax.swing.JButton();
        R302 = new javax.swing.JButton();
        R303 = new javax.swing.JButton();
        R304 = new javax.swing.JButton();
        R305 = new javax.swing.JButton();
        floor2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        R201 = new javax.swing.JButton();
        R202 = new javax.swing.JButton();
        R203 = new javax.swing.JButton();
        R204 = new javax.swing.JButton();
        R205 = new javax.swing.JButton();
        floor1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        R101 = new javax.swing.JButton();
        R102 = new javax.swing.JButton();
        R103 = new javax.swing.JButton();
        R104 = new javax.swing.JButton();
        R105 = new javax.swing.JButton();

        jPageHeadPanel.setBackground(new java.awt.Color(146, 177, 204));

        jPageLabel.setFont(new java.awt.Font("Angsana New", 1, 48)); // NOI18N
        jPageLabel.setForeground(new java.awt.Color(30, 91, 145));
        jPageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPageLabel.setText("Room");

        javax.swing.GroupLayout jPageHeadPanelLayout = new javax.swing.GroupLayout(jPageHeadPanel);
        jPageHeadPanel.setLayout(jPageHeadPanelLayout);
        jPageHeadPanelLayout.setHorizontalGroup(
            jPageHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPageHeadPanelLayout.setVerticalGroup(
            jPageHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        jBodyPanel.setBackground(new java.awt.Color(234, 242, 249));

        jDateLabel.setFont(new java.awt.Font("Angsana New", 1, 48)); // NOI18N
        jDateLabel.setText("Date");

        floor3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel17.setText("ชั้น 3");

        R301.setBackground(new java.awt.Color(216, 255, 186));
        R301.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R301.setText("301");
        R301.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R301.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R301.setMaximumSize(new java.awt.Dimension(150, 45));
        R301.setMinimumSize(new java.awt.Dimension(150, 45));
        R301.setPreferredSize(new java.awt.Dimension(150, 45));
        R301.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R301ActionPerformed(evt);
            }
        });

        R302.setBackground(new java.awt.Color(216, 255, 186));
        R302.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R302.setText("302");
        R302.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R302.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R302.setMaximumSize(new java.awt.Dimension(150, 45));
        R302.setMinimumSize(new java.awt.Dimension(150, 45));
        R302.setPreferredSize(new java.awt.Dimension(150, 45));
        R302.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R302ActionPerformed(evt);
            }
        });

        R303.setBackground(new java.awt.Color(216, 255, 186));
        R303.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R303.setText("303");
        R303.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R303.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R303.setMaximumSize(new java.awt.Dimension(150, 45));
        R303.setMinimumSize(new java.awt.Dimension(150, 45));
        R303.setPreferredSize(new java.awt.Dimension(150, 45));
        R303.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R303ActionPerformed(evt);
            }
        });

        R304.setBackground(new java.awt.Color(216, 255, 186));
        R304.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R304.setText("304");
        R304.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R304.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R304.setMaximumSize(new java.awt.Dimension(150, 45));
        R304.setMinimumSize(new java.awt.Dimension(150, 45));
        R304.setPreferredSize(new java.awt.Dimension(150, 45));
        R304.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R304ActionPerformed(evt);
            }
        });

        R305.setBackground(new java.awt.Color(216, 255, 186));
        R305.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R305.setText("305");
        R305.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R305.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R305.setMaximumSize(new java.awt.Dimension(150, 45));
        R305.setMinimumSize(new java.awt.Dimension(150, 45));
        R305.setPreferredSize(new java.awt.Dimension(150, 45));
        R305.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R305ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout floor3Layout = new javax.swing.GroupLayout(floor3);
        floor3.setLayout(floor3Layout);
        floor3Layout.setHorizontalGroup(
            floor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floor3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(R301, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R302, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R303, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R304, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R305, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        floor3Layout.setVerticalGroup(
            floor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(floor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(R301, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R302, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R303, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R304, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R305, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        floor2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel16.setText("ชั้น 2");

        R201.setBackground(new java.awt.Color(216, 255, 186));
        R201.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R201.setText("201");
        R201.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R201.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R201.setMaximumSize(new java.awt.Dimension(150, 45));
        R201.setMinimumSize(new java.awt.Dimension(150, 45));
        R201.setPreferredSize(new java.awt.Dimension(150, 45));
        R201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R201ActionPerformed(evt);
            }
        });

        R202.setBackground(new java.awt.Color(216, 255, 186));
        R202.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R202.setText("202");
        R202.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R202.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R202.setMaximumSize(new java.awt.Dimension(150, 45));
        R202.setMinimumSize(new java.awt.Dimension(150, 45));
        R202.setPreferredSize(new java.awt.Dimension(150, 45));
        R202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R202ActionPerformed(evt);
            }
        });

        R203.setBackground(new java.awt.Color(216, 255, 186));
        R203.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R203.setText("203");
        R203.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R203.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R203.setMaximumSize(new java.awt.Dimension(150, 45));
        R203.setMinimumSize(new java.awt.Dimension(150, 45));
        R203.setPreferredSize(new java.awt.Dimension(150, 45));
        R203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R203ActionPerformed(evt);
            }
        });

        R204.setBackground(new java.awt.Color(216, 255, 186));
        R204.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R204.setText("204");
        R204.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R204.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R204.setMaximumSize(new java.awt.Dimension(150, 45));
        R204.setMinimumSize(new java.awt.Dimension(150, 45));
        R204.setPreferredSize(new java.awt.Dimension(150, 45));
        R204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R204ActionPerformed(evt);
            }
        });

        R205.setBackground(new java.awt.Color(216, 255, 186));
        R205.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R205.setText("205");
        R205.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R205.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R205.setMaximumSize(new java.awt.Dimension(150, 45));
        R205.setMinimumSize(new java.awt.Dimension(150, 45));
        R205.setPreferredSize(new java.awt.Dimension(150, 45));
        R205.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R205ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout floor2Layout = new javax.swing.GroupLayout(floor2);
        floor2.setLayout(floor2Layout);
        floor2Layout.setHorizontalGroup(
            floor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floor2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(R201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R202, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R203, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R204, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R205, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        floor2Layout.setVerticalGroup(
            floor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(floor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(R201, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R202, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R203, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R204, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R205, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        floor1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel15.setText("ชั้น 1");

        R101.setBackground(new java.awt.Color(216, 255, 186));
        R101.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R101.setText("101");
        R101.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R101.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R101.setMaximumSize(new java.awt.Dimension(150, 45));
        R101.setMinimumSize(new java.awt.Dimension(150, 45));
        R101.setPreferredSize(new java.awt.Dimension(150, 45));
        R101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R101ActionPerformed(evt);
            }
        });

        R102.setBackground(new java.awt.Color(216, 255, 186));
        R102.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R102.setText("102");
        R102.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R102.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R102.setMaximumSize(new java.awt.Dimension(150, 45));
        R102.setMinimumSize(new java.awt.Dimension(150, 45));
        R102.setPreferredSize(new java.awt.Dimension(150, 45));
        R102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R102ActionPerformed(evt);
            }
        });

        R103.setBackground(new java.awt.Color(216, 255, 186));
        R103.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R103.setText("103");
        R103.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R103.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R103.setMaximumSize(new java.awt.Dimension(150, 45));
        R103.setMinimumSize(new java.awt.Dimension(150, 45));
        R103.setPreferredSize(new java.awt.Dimension(150, 45));
        R103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R103ActionPerformed(evt);
            }
        });

        R104.setBackground(new java.awt.Color(216, 255, 186));
        R104.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R104.setText("104");
        R104.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R104.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R104.setMaximumSize(new java.awt.Dimension(150, 45));
        R104.setMinimumSize(new java.awt.Dimension(150, 45));
        R104.setPreferredSize(new java.awt.Dimension(150, 45));
        R104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R104ActionPerformed(evt);
            }
        });

        R105.setBackground(new java.awt.Color(216, 255, 186));
        R105.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        R105.setText("105");
        R105.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        R105.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        R105.setMaximumSize(new java.awt.Dimension(150, 45));
        R105.setMinimumSize(new java.awt.Dimension(150, 45));
        R105.setPreferredSize(new java.awt.Dimension(150, 45));
        R105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R105ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout floor1Layout = new javax.swing.GroupLayout(floor1);
        floor1.setLayout(floor1Layout);
        floor1Layout.setHorizontalGroup(
            floor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floor1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(R101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(R105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        floor1Layout.setVerticalGroup(
            floor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(floor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(R101, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R102, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R103, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R104, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(R105, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jBodyPanelLayout = new javax.swing.GroupLayout(jBodyPanel);
        jBodyPanel.setLayout(jBodyPanelLayout);
        jBodyPanelLayout.setHorizontalGroup(
            jBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(floor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jBodyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(floor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(floor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jBodyPanelLayout.setVerticalGroup(
            jBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBodyPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jDateLabel)
                .addGap(35, 35, 35)
                .addComponent(floor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(floor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(floor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPageHeadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPageHeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void R101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R101ActionPerformed
        BookingForm.getBookingForm("ห้อง 101");
    }//GEN-LAST:event_R101ActionPerformed

    private void R102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R102ActionPerformed
        BookingForm.getBookingForm("ห้อง 102");
    }//GEN-LAST:event_R102ActionPerformed

    private void R201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R201ActionPerformed
        BookingForm.getBookingForm("ห้อง 201");
    }//GEN-LAST:event_R201ActionPerformed

    private void R202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R202ActionPerformed
        BookingForm.getBookingForm("ห้อง 202");
    }//GEN-LAST:event_R202ActionPerformed

    private void R301ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R301ActionPerformed
        BookingForm.getBookingForm("ห้อง 301");
    }//GEN-LAST:event_R301ActionPerformed

    private void R302ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R302ActionPerformed
        BookingForm.getBookingForm("ห้อง 302");
    }//GEN-LAST:event_R302ActionPerformed

    private void R303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R303ActionPerformed
        BookingForm.getBookingForm("ห้อง 303");
    }//GEN-LAST:event_R303ActionPerformed

    private void R304ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R304ActionPerformed
        BookingForm.getBookingForm("ห้อง 304");
    }//GEN-LAST:event_R304ActionPerformed

    private void R305ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R305ActionPerformed
        BookingForm.getBookingForm("ห้อง 305");
    }//GEN-LAST:event_R305ActionPerformed

    private void R204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R204ActionPerformed
        BookingForm.getBookingForm("ห้อง 204");
    }//GEN-LAST:event_R204ActionPerformed

    private void R205ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R205ActionPerformed
        BookingForm.getBookingForm("ห้อง 205");
    }//GEN-LAST:event_R205ActionPerformed

    private void R203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R203ActionPerformed
        BookingForm.getBookingForm("ห้อง 203");
    }//GEN-LAST:event_R203ActionPerformed

    private void R103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R103ActionPerformed
        BookingForm.getBookingForm("ห้อง 103");
    }//GEN-LAST:event_R103ActionPerformed

    private void R104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R104ActionPerformed
        BookingForm.getBookingForm("ห้อง 104");
    }//GEN-LAST:event_R104ActionPerformed

    private void R105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R105ActionPerformed
        BookingForm.getBookingForm("ห้อง 105");
    }//GEN-LAST:event_R105ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton R101;
    private javax.swing.JButton R102;
    private javax.swing.JButton R103;
    private javax.swing.JButton R104;
    private javax.swing.JButton R105;
    private javax.swing.JButton R201;
    private javax.swing.JButton R202;
    private javax.swing.JButton R203;
    private javax.swing.JButton R204;
    private javax.swing.JButton R205;
    private javax.swing.JButton R301;
    private javax.swing.JButton R302;
    private javax.swing.JButton R303;
    private javax.swing.JButton R304;
    private javax.swing.JButton R305;
    private javax.swing.JPanel floor1;
    private javax.swing.JPanel floor2;
    private javax.swing.JPanel floor3;
    private javax.swing.JPanel jBodyPanel;
    private javax.swing.JLabel jDateLabel;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPageHeadPanel;
    private javax.swing.JLabel jPageLabel;
    // End of variables declaration//GEN-END:variables
}
